dist: bionic
env:
    global:
        - PACKAGE="AutoSetIndentation" # Package name
        - SUBLIME_TEXT_VERSION="3"
language: python
python:
    - "3.7"
install:
    - python -m pip install -U pip
    - pip install -U -r requirements.txt
script:
    - mypy -p plugin
    - black --check .
