dist: bionic
env:
    global:
        - PACKAGE="AutoSetIndentation" # Package name
        - SUBLIME_TEXT_VERSION="3"
language: python
python:
    - "3.7"
before_install:
    # remove potential mypy cache
    - rm -rf .mypy_cache/
install:
    - python -m pip install -U pip
    - pip install -U -r requirements.txt
script:
    - mypy -p plugin
    - flake8 plugin
    - black --check .
